DROP TABLE IF EXISTS Actors;

CREATE TABLE Actors(
	Name VARCHAR(40) NOT NULL,
	Movie VARCHAR(80),
	Year INT,
	Role VARCHAR(40) NOT NULL
)ENGINE = INNODB;

LOAD DATA LOCAL INFILE '~/data/actors.csv' INTO TABLE Actors FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

SELECT * FROM Actors WHERE Year < 2000;
SELECT COUNT(*) FROM Actors;
SELECT COUNT(*) FROM Actors WHERE Movie = "Chicago";


DROP TABLE IF EXISTS Actors;